### ISSUE TITLE
Could you please refrain from saying "@tutti" in your comments?

### ISSUE THREAD

**Issue by tutti** [edmondo/wasteland2#17]
I've been getting notifications for your project for some time, and it took me some digging to figure out why - you mentioned me in a comment. I see how it happened, but since I have no interest in your project and don't speak your language it would be nice if you could avoid that. Thanks.

**Comment by edmondo** [comment]
Uh, sorry about that. Unfortunately your nickname is a common italian word and we have some technical references to this common word with a leading @ . It has nothing to do with you, it's just an unfortunate case. So sorry.

Now, the good thing is that you can disable notifications for specific projects yourself. Just select this project and select Ignore instead of Watch/Unwatch on the right side. Here a screenshot telling you were:

![github_unwatch](https://cloud.githubusercontent.com/assets/1729650/4871613/7910a762-61c0-11e4-8079-6436e076bfd2.jpg)

I hope it helps. If you have other issues, please let me know.

**Comment by tutti** [comment]
Oh, I didn't know that existed, I looked for something like that earlier (I had bothering you as my last resort) but must've missed it. Thanks for the tip :)
